python data/TACRED/TACRED_create_episodes_uniform.py --file_name data/TACRED/revisited/3_TACRED_REVISITED_split/3_test_data.json --episodes_size 10000 --N 5 --K 5 --number_of_queries 3 --seed 160290 --output_file_name data/TACRED/revisited/3_TACRED_REVISITED_split/test_episodes/3_split_5way_5shots_10K_episodes_3q_seed_160290.json &
python data/TACRED/TACRED_create_episodes_uniform.py --file_name data/TACRED/revisited/3_TACRED_REVISITED_split/3_test_data.json --episodes_size 10000 --N 5 --K 5 --number_of_queries 3 --seed 160291 --output_file_name data/TACRED/revisited/3_TACRED_REVISITED_split/test_episodes/3_split_5way_5shots_10K_episodes_3q_seed_160291.json &
python data/TACRED/TACRED_create_episodes_uniform.py --file_name data/TACRED/revisited/3_TACRED_REVISITED_split/3_test_data.json --episodes_size 10000 --N 5 --K 5 --number_of_queries 3 --seed 160292 --output_file_name data/TACRED/revisited/3_TACRED_REVISITED_split/test_episodes/3_split_5way_5shots_10K_episodes_3q_seed_160292.json &
python data/TACRED/TACRED_create_episodes_uniform.py --file_name data/TACRED/revisited/3_TACRED_REVISITED_split/3_test_data.json --episodes_size 10000 --N 5 --K 5 --number_of_queries 3 --seed 160293 --output_file_name data/TACRED/revisited/3_TACRED_REVISITED_split/test_episodes/3_split_5way_5shots_10K_episodes_3q_seed_160293.json &
python data/TACRED/TACRED_create_episodes_uniform.py --file_name data/TACRED/revisited/3_TACRED_REVISITED_split/3_test_data.json --episodes_size 10000 --N 5 --K 5 --number_of_queries 3 --seed 160294 --output_file_name data/TACRED/revisited/3_TACRED_REVISITED_split/test_episodes/3_split_5way_5shots_10K_episodes_3q_seed_160294.json &
python data/TACRED/TACRED_create_episodes_uniform.py --file_name data/TACRED/revisited/3_TACRED_REVISITED_split/3_test_data.json --episodes_size 10000 --N 5 --K 1 --number_of_queries 3 --seed 160290 --output_file_name data/TACRED/revisited/3_TACRED_REVISITED_split/test_episodes/3_split_5way_1shots_10K_episodes_3q_seed_160290.json &
python data/TACRED/TACRED_create_episodes_uniform.py --file_name data/TACRED/revisited/3_TACRED_REVISITED_split/3_test_data.json --episodes_size 10000 --N 5 --K 1 --number_of_queries 3 --seed 160291 --output_file_name data/TACRED/revisited/3_TACRED_REVISITED_split/test_episodes/3_split_5way_1shots_10K_episodes_3q_seed_160291.json &
python data/TACRED/TACRED_create_episodes_uniform.py --file_name data/TACRED/revisited/3_TACRED_REVISITED_split/3_test_data.json --episodes_size 10000 --N 5 --K 1 --number_of_queries 3 --seed 160292 --output_file_name data/TACRED/revisited/3_TACRED_REVISITED_split/test_episodes/3_split_5way_1shots_10K_episodes_3q_seed_160292.json &
python data/TACRED/TACRED_create_episodes_uniform.py --file_name data/TACRED/revisited/3_TACRED_REVISITED_split/3_test_data.json --episodes_size 10000 --N 5 --K 1 --number_of_queries 3 --seed 160293 --output_file_name data/TACRED/revisited/3_TACRED_REVISITED_split/test_episodes/3_split_5way_1shots_10K_episodes_3q_seed_160293.json &
python data/TACRED/TACRED_create_episodes_uniform.py --file_name data/TACRED/revisited/3_TACRED_REVISITED_split/3_test_data.json --episodes_size 10000 --N 5 --K 1 --number_of_queries 3 --seed 160294 --output_file_name data/TACRED/revisited/3_TACRED_REVISITED_split/test_episodes/3_split_5way_1shots_10K_episodes_3q_seed_160294.json &

